### PR TITLE
fix: Tutorial 2, finetune a model, distillation code

### LINKED ISSUE #67: Tutorial 2 - Finetune a model : `fetch_archive_from_http` called twice with same output_dir
**Describe the issue**
In tutorial 2, Fine-tuning a Model on Your Own Data, tool `fetch_archive_from_http` is called twice with the same output_dir [here](https://github.com/deepset-ai/haystack-tutorials/blob/main/tutorials/02_Finetune_a_model_on_your_data.ipynb?short_path=d2d23af#L226) and [here](https://github.com/deepset-ai/haystack-tutorials/blob/main/tutorials/02_Finetune_a_model_on_your_data.ipynb?short_path=d2d23af#L230) with the same output_dir this can't work because it will only download if the folder is empty (see [implementation and warning here](https://github.com/deepset-ai/haystack/blob/main/haystack/utils/import_utils.py#L84)).

More over path are incorrect when calling `augment_squad.py`. 

I will push a PR with a fix.

**To Reproduce**
- Simply run the code in Distill your model, it won't work without modifying it

**Expected behavior**
A clear and concise description of what you expected to happen : 
- it should download glove vectors AND squad_small.json

**What environment did you try to run the tutorial on?:**
 - OS: All
 - Browser : Chrome
 - Haystack Version : Latest

**Additional context**

### PR DESCRIPTION
**Pull request by Benvii**
Fixes #67.

Use 2 different download location so that glove vectors AND squad small are downloaded.

Thanks in advance for the review 🙂

### CODE REVIEW

**Comment by TuanaCelik** [comment]
Good catch! Lgtm, wdyt @julian-risch

**Comment by Benvii** [comment]
Rebased to avoid conflict on the markdown file.
@julian-risch is it good for you ?

**Review by julian-risch — APPROVED** [review]
The changes look good to me and the fix they linked issue. 👍 Thank you for your contribution @Benvii ! We will take care of merging your PR.

**Comment by Benvii** [comment]
Hi @julian-risch thanks for the merging, pipeline seems to fail, don't hesitate if you need any help

**Comment by TuanaCelik** [comment]
Hey @Benvii - If it's ok with you, I've just checked out on your forked repo and the branch here. I will merge master into your branch, re-generate the markdown and push a new commit.

**Review by TuanaCelik — APPROVED** [review]

**Pull request merged**
