### PR TITLE
First commit for adding the download path to the frontmatter

### PR DESCRIPTION
**Pull request by TuanaCelik**
In this PR, I also make it so that the first line of the .ipynb is excluded while generating markdowns. This way we can display it wherever we want on HSH

I've generated the new markdown for tutorial 1 only for now. @masci if you agree this is a good implementation let me know.

@brandenchan tagging you here so that you're aware too. On top of this I'll also create a PR for the 'slugs' that we can also have a look at together

### CODE REVIEW

**Review by masci — APPROVED** [review]
Implementation LGTM, we should amend the Hugo template to show `.Title` before merging this one, correct?

**Comment by TuanaCelik** [comment]
> Implementation LGTM, we should amend the Hugo template to show `.Title` before merging this one, correct?

Indeed but also I'll generate markdowns for the rest of the tutorials too :)

**Comment by TuanaCelik** [comment]
@brandenchan - This is the PR that adds the 'download' button to the tutorials, and also does the 'Title' trick that I explained to you on our call. If you're ok with that, I will update all of the tutorials here and merge. Just checking again that you consent to this experiment so that we can have the button below the title :)

**Comment by brandenchan** [comment]
> @brandenchan - This is the PR that adds the 'download' button to the tutorials, and also does the 'Title' trick that I explained to you on our call. If you're ok with that, I will update all of the tutorials here and merge. Just checking again that you consent to this experiment so that we can have the button below the title :)

Ok go ahead

**Comment by TuanaCelik** [comment]
Updated the download links to all PRs here. I excluded the 19th as Bilge is fixing the fact that the notebook did not have a title in #74 - @bilgeyucel when this PR is merged you might want to merge it into your PR and generate markdown again. It will remove the first line (so the title) - which HSH will add itself

**Pull request merged**
