### PR TITLE
Update 22_Pipeline_with_PromptNode.ipynb

### PR DESCRIPTION
**Pull request by JetQin**

### CODE REVIEW

**Comment by JetQin** [comment]
for dataset 2.2.1 version, it use _type keyword to fetch check the condition,  so the dataset must have a column _type, I create another dataset rename the column 'content_type'  to 'type'
```
    class_type = globals()[obj.pop("_type")]

    if class_type == Sequence:
        return Sequence(feature=generate_from_dict(obj["feature"]), length=obj["length"])
```

**Comment by mayankjobanputra** [comment]
@bilgeyucel @TuanaCelik Are we already planning to move the dataset under Deepset repository? I haven't checked if the suggestion is already working or not.

**Comment by TuanaCelik** [comment]
Thanks for the contribution @JetQin 🙌 But as far as I can tell, changing this field to `_type` would contradict our use case here. Each document in this dataset is meant to be a complete and useable Haystack Document type, which expects the `content_type` field not `_type`. 
@mayankjobanputra any ideas with regards the check they mention?

**Comment by bilgeyucel** [comment]
Hey @JetQin, I checked the HF documentation but couldn't find any information regarding `_type`. Can you share more info about this field? 
If necessary for this dataset, we can have both `content_type` and `_type` columns on HF. Later, we can use `_type` as metadata for Documents or drop it before indexing the dataset.

**Comment by mayankjobanputra** [comment]
@TuanaCelik @bilgeyucel I am getting an error when I use `datasets==2.2.1`. I am investigating the issue further. Will post here. :)

**Comment by mayankjobanputra** [comment]
I didn't get any errors with the latest default version of `datasets`.

**Comment by mayankjobanputra** [comment]
@TuanaCelik @bilgeyucel @JetQin I confirmed we wouldn't encounter the issue for `pip install datasets>=2.6.0`. I don't think we should support older versions, the best thing we should do is make sure to install `datasets>=2.6.0`.

wdyt??

**Comment by JetQin** [comment]
@mayankjobanputra  try with version 2.6.1, it works.  so I think it would be better to specify the exact version number. I just update the version number.
截屏2023-03-29 06 43 29

but in version 2.2. it will throw exception.
截屏2023-03-29 06 48 00

**Comment by mayankjobanputra** [comment]
@TuanaCelik @bilgeyucel Changes look ok to me. wdyt?

**Comment by mayankjobanputra** [comment]
@JetQin I think it's better to not pin the `datasets` version to just one version because I randomly tested with 10 versions and it works with all the versions after `2.6.0`. I am reverting to `>=2.6.0`

**Review by TuanaCelik — APPROVED** [review]

**Comment by TuanaCelik** [comment]
Looks good to me folks, thanks! @bilgeyucel I'll let you decide whether we merge this or not as it's your tutorial

**Comment by mayankjobanputra** [comment]
I had a chat with @bilgeyucel. Merging this :)

**Comment by mayankjobanputra** [comment]
@JetQin Thanks for contributing this one :) Kudos on your first contribution. :1st_place_medal: 

Looking forward to more contributions from you :) :tada:

**Pull request merged**
