### PR TITLE
Preprocessing.md: fix typo

### PR DESCRIPTION
**Pull request by blancadesal**

### CODE REVIEW

**Comment by anakin87** [comment]
Hello @blancadesal!

Thanks for the contribution.

To modify to the tutorials, you should edit the ipynb notebook then generate the updated markdown files as specified [here](https://github.com/deepset-ai/haystack-tutorials/blob/main/Contributing.md#contributing-edits-or-new-tutorials).

Probably it was not very clear. @bilgeyucel is currenty improving the contributing guide (https://github.com/deepset-ai/haystack-tutorials/pull/119).

**Comment by blancadesal** [comment]
Oh, ok! Thanks for the link. I've amended my commit; however, when I ran pre-commit, black-jupyter and md version of tutorials formatted a whole bunch (20+) of files. Was that to be expected? It feels wrong to include them in this PR as they are unrelated to the typo fix.

**Comment by anakin87** [comment]
It seems strange. 🤔 

I think you should only include the ipynb notebook and the generated markdown in this PR.

**Comment by anakin87** [comment]
@TuanaCelik @bilgeyucel this PR seems good to me.
Please approve the workflows to run checks.
:heart_decoration:

**Review by anakin87 — APPROVED** [review]

**Comment by blancadesal** [comment]
> however, when I ran pre-commit, black-jupyter and md version of tutorials formatted a whole bunch (20+) of files. Was that to be expected? It feels wrong to include them in this PR as they are unrelated to the typo fix.

Hmm, it does seem like this is the only way to make CI pass though, at least locally.

**Review by bilgeyucel — APPROVED** [review]

**Comment by bilgeyucel** [comment]
Hey @blancadesal, thank you for your contribution! I had to checkout to your branch to update the last_updated timestamp one last time. This problem is basically because of a bug in our workflows, but we're working to solve it so this problem doesn't happen again. Again, thank you, and this PR is merged! 💯 🚀

**Comment by blancadesal** [comment]
Thank you for sorting this out @bilgeyucel !

**Pull request merged**
