### PR TITLE
`preprocessing`, `file-conversion`, and `elasticsearch` extras

### LINKED ISSUE #166: ElasticsearchDocumentStore is in a optional dependency
Install one extra dependency in the tutorials with `ElasticsearchDocumentStore`. So, `pip install farm-haystack[elasticsearch]`. Check the [Haystack PR](https://github.com/deepset-ai/haystack/pull/4668) for details. 

This is also an opportunity to switch to InMemoryDocumentStore for some of them 👀  -> Issue #153

### PR DESCRIPTION
**Pull request by ZanSara**
See https://github.com/deepset-ai/haystack/pull/4605/

- fixes #166

### CODE REVIEW

**Review by TuanaCelik — APPROVED** [review]

**Review by bilgeyucel — APPROVED** [review]

**Comment by bilgeyucel** [comment]
Let's wait for the release to merge this. Otherwise, tests will pass but notebooks will raise errors when run locally or on Colab.

**Comment by ZanSara** [comment]
I'll add a related issue to the 1.16 milestone :+1:

**Comment by TuanaCelik** [comment]
Leaving a note here that there might be some merge conflicts once the #167 PR is merged

**Comment by bogdankostic** [comment]
I resolved the merge conflicts and added the `elasticsearch` extra to those tutorials that use an `ElasticsearchDocumentStore` (needed after releasing Haystack with this PR: https://github.com/deepset-ai/haystack/pull/4668/)

**Pull request merged**
